[theme]
base = "dark"
primaryColor = "#ED1C24"
backgroundColor = "#050B14"
secondaryBackgroundColor = "#0B1727"
textColor = "#F4F7FB"
font = "sans serif"

[server]
maxUploadSize = 128
fileWatcherType = "none"
