[theme]
base = "light"
primaryColor = "#ED1C24"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F6F8"
textColor = "#171717"
font = "sans serif"

[server]
maxUploadSize = 128
fileWatcherType = "none"
